"use client";
import { useState } from "react";

type Variant = { id: string; sku: string; title: string; priceMinor: number | null; inventory?: { id: string; onHand: number; reserved: number } | null };
export default function VariantManager({ productId, variants }: { productId: string; variants: Variant[] }) {
  const [rows, setRows] = useState(variants); const [sku, setSku] = useState(""); const [title, setTitle] = useState(""); const [stock, setStock] = useState("0"); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setNotice(""); const response = await fetch(`/api/admin/products/${productId}/variants`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sku, title, openingStock: Number(stock) }) }); const body = await response.json() as Variant & { error?: string }; if (!response.ok) setNotice(body.error || "Unable to create variant."); else { setRows([...rows, body]); setSku(""); setTitle(""); setStock("0"); setNotice("Variant created with an opening inventory movement."); } setBusy(false); }
  return <section className="variantManager"><div className="adminSubhead"><div><div className="eyebrow">Variants & inventory</div><h3>Sellable options</h3></div></div>{rows.length ? <table className="adminTable"><thead><tr><th>Variant</th><th>SKU</th><th>On hand</th><th>Reserved</th></tr></thead><tbody>{rows.map((variant) => <tr key={variant.id}><td>{variant.title}</td><td>{variant.sku}</td><td>{variant.inventory?.onHand ?? 0}</td><td>{variant.inventory?.reserved ?? 0}</td></tr>)}</tbody></table> : <p className="muted">No variants yet. Add the sellable sizes, colours, or materials for this product.</p>}<form className="variantForm" onSubmit={submit}><input className="field" placeholder="Variant title — e.g. Camel / M" value={title} onChange={(event) => setTitle(event.target.value)} required /><input className="field" placeholder="SKU" value={sku} onChange={(event) => setSku(event.target.value)} required /><input className="field" type="number" min="0" placeholder="Opening stock" value={stock} onChange={(event) => setStock(event.target.value)} required /><button className="btn dark" disabled={busy}>{busy ? "Adding…" : "Add variant"}</button></form>{notice && <p className="muted">{notice}</p>}</section>;
}
