export type AdminRole='OWNER'|'ADMIN'|'MANAGER'|'SALES'|'INVENTORY'|'FACTORY'|'CONTENT'|'SUPPORT'|'VIEWER';
export type Permission='admin.access'|'dashboard.read'|'products.read'|'products.write'|'collections.read'|'collections.write'|'inventory.read'|'inventory.adjust'|'orders.read'|'orders.write'|'customers.read'|'customers.write'|'whatsapp.read'|'whatsapp.write'|'wholesale.read'|'wholesale.write'|'payments.read'|'payments.refund'|'shipping.read'|'shipping.write'|'returns.read'|'returns.write'|'users.read'|'users.write'|'audit.read'|'content.read'|'content.write'|'factory.read'|'factory.write'|'analytics.read';
export type AdminActor={id:string;email:string;role:AdminRole;permissions:Permission[];name:string};
const all:Permission[]=['admin.access','dashboard.read','products.read','products.write','collections.read','collections.write','inventory.read','inventory.adjust','orders.read','orders.write','customers.read','customers.write','whatsapp.read','whatsapp.write','wholesale.read','wholesale.write','payments.read','payments.refund','shipping.read','shipping.write','returns.read','returns.write','users.read','users.write','audit.read','content.read','content.write','factory.read','factory.write','analytics.read'];
export const rolePermissions:Record<AdminRole,Permission[]>={OWNER:all,ADMIN:all.filter(p=>!['factory.write'].includes(p)),MANAGER:['admin.access','dashboard.read','products.read','collections.read','inventory.read','orders.read','orders.write','customers.read','customers.write','whatsapp.read','whatsapp.write','wholesale.read','wholesale.write','payments.read','shipping.read','returns.read','returns.write','analytics.read'],SALES:['admin.access','dashboard.read','customers.read','customers.write','orders.read','orders.write','whatsapp.read','whatsapp.write','wholesale.read','wholesale.write'],INVENTORY:['admin.access','products.read','products.write','collections.read','inventory.read','inventory.adjust','shipping.read'],FACTORY:['admin.access','products.read','inventory.read','factory.read','factory.write'],CONTENT:['admin.access','products.read','products.write','collections.read','collections.write','content.read','content.write'],SUPPORT:['admin.access','customers.read','customers.write','orders.read','orders.write','whatsapp.read','whatsapp.write','returns.read','returns.write'],VIEWER:['admin.access','dashboard.read','analytics.read']};
export const hasPermission=(actor:AdminActor,permission:Permission)=>actor.permissions.includes(permission);
export type AuthConfiguration={provider:'unconfigured'|'external';configured:boolean}; export const authConfiguration:AuthConfiguration={provider:'unconfigured',configured:false};
/** Server-only identity boundary. Implement using a verified provider session; never trust browser role data. */
export interface AdminAuthService{getActor():Promise<AdminActor|null>;require(permission:Permission):Promise<AdminActor>;}
export const adminAuthService:AdminAuthService={async getActor(){return null},async require(){throw new Error('Admin authentication is not configured.')}};
