import type { Customer } from './customers';
export type OrderStatus = 'pending' | 'payment_pending' | 'paid' | 'processing' | 'packed' | 'shipped' | 'delivered' | 'cancelled' | 'refund_requested' | 'refunded';
export type OrderSource = 'website' | 'whatsapp' | 'wholesale' | 'manual';
export type PaymentStatus = 'pending' | 'paid' | 'refunded' | 'unavailable'; export type FulfillmentStatus = 'unfulfilled' | 'processing' | 'packed' | 'shipped' | 'delivered' | 'unavailable';
export type OrderLine = { id: string; productId: string; variantId: string | null; name: string; sku: string | null; quantity: number; unitPrice: number; total: number };
export type OrderTimelineEvent = { id: string; type: 'created' | 'payment_received' | 'confirmed' | 'processing_started' | 'packed' | 'shipped' | 'delivered'; timestamp: string; actor: string; reference: string | null };
export type Order = { id: string; number: string; customerId: string; status: OrderStatus; paymentStatus: PaymentStatus; fulfillmentStatus: FulfillmentStatus; source: OrderSource; currency: string; lines: OrderLine[]; subtotal: number; discounts: number; shipping: number; tax: number | null; total: number; paymentMethod: string | null; shippingAddress: Customer['addresses'][number] | null; billingAddress: Customer['addresses'][number] | null; internalNotes: string[]; timeline: OrderTimelineEvent[]; createdAt: string; updatedAt: string };
export type OrderMutationResult = { ok: false; reason: 'persistence_unavailable'; message: string };
const transitions: Record<OrderStatus, OrderStatus[]> = { pending:['payment_pending','paid','cancelled'], payment_pending:['paid','cancelled'], paid:['processing','refund_requested','refunded'], processing:['packed','cancelled'], packed:['shipped'], shipped:['delivered','refund_requested'], delivered:['refund_requested','refunded'], cancelled:[], refund_requested:['refunded'], refunded:[] };
export const canTransition = (from: OrderStatus, to: OrderStatus) => transitions[from].includes(to);
export interface OrderService { list(query?: string): Promise<{ state: 'unavailable' | 'live'; orders: Order[] }>; get(id: string): Promise<Order | null>; updateStatus(id: string, next: OrderStatus): Promise<OrderMutationResult>; updatePaymentStatus(id: string, status: PaymentStatus): Promise<OrderMutationResult>; updateFulfillmentStatus(id: string, status: FulfillmentStatus): Promise<OrderMutationResult>; addInternalNote(id: string, note: string): Promise<OrderMutationResult>; }
const unavailable = (): OrderMutationResult => ({ ok: false, reason: 'persistence_unavailable', message: 'Order data is not connected; no status or internal-note change was saved.' });
export const orderService: OrderService = { async list() { return { state: 'unavailable', orders: [] }; }, async get() { return null; }, async updateStatus() { return unavailable(); }, async updatePaymentStatus() { return unavailable(); }, async updateFulfillmentStatus() { return unavailable(); }, async addInternalNote() { return unavailable(); } };
