import type { Customer } from './customers'; import type { Order } from './orders';
export type WhatsAppInquiryStatus = 'new' | 'contacted' | 'negotiating' | 'order_confirmed' | 'converted' | 'lost' | 'closed';
export type WhatsAppInquiry = { id: string; customerId: string | null; customer: Pick<Customer, 'id'|'name'|'phone'> | null; productId: string | null; variantId: string | null; quantity: number | null; status: WhatsAppInquiryStatus; assignedStaffId: string | null; notes: string[]; createdAt: string; followUpAt: string | null; conversionStatus: 'not_converted' | 'ready_to_convert' | 'converted'; source: string | null };
export type InquiryMutationResult = { ok: false; reason: 'persistence_unavailable'; message: string; order?: Order };
const transitions: Record<WhatsAppInquiryStatus, WhatsAppInquiryStatus[]> = { new:['contacted','lost','closed'], contacted:['negotiating','lost','closed'], negotiating:['order_confirmed','lost','closed'], order_confirmed:['converted','lost','closed'], converted:[], lost:['closed'], closed:[] };
export const canTransitionInquiry = (from: WhatsAppInquiryStatus, to: WhatsAppInquiryStatus) => transitions[from].includes(to);
export interface WhatsAppInquiryService { list(query?: string): Promise<{ state:'unavailable'|'live'; inquiries:WhatsAppInquiry[] }>; get(id:string):Promise<WhatsAppInquiry|null>; assign(id:string,staffId:string):Promise<InquiryMutationResult>; addNote(id:string,note:string):Promise<InquiryMutationResult>; setFollowUp(id:string,date:string):Promise<InquiryMutationResult>; updateStatus(id:string,status:WhatsAppInquiryStatus):Promise<InquiryMutationResult>; convertToOrder(id:string):Promise<InquiryMutationResult>; }
const unavailable=():InquiryMutationResult=>({ok:false,reason:'persistence_unavailable',message:'WhatsApp CRM data is not connected; no inquiry or order conversion was saved.'});
/** Internal CRM adapter. Replace with a configured WhatsApp Business/API ingestion provider when available. */
export const whatsAppInquiryService:WhatsAppInquiryService={async list(){return {state:'unavailable',inquiries:[]}},async get(){return null},async assign(){return unavailable()},async addNote(){return unavailable()},async setFollowUp(){return unavailable()},async updateStatus(){return unavailable()},async convertToOrder(){return unavailable()}};
